### PR TITLE
Avoid using readonly for public exposed reactive properties

### LINKED ISSUE #240: [v2.2.1] Auth0Plugin is incompatible with Auth0VueClient (exactOptionalPropertyTypes: true)
### Checklist

- [X] The issue can be reproduced in the [auth0-vue sample app](https://github.com/auth0-samples/auth0-vue-samples/tree/master/01-Login) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-vue#readme), [Examples](https://github.com/auth0/auth0-vue/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-vue/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-vue/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-vue/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After updating to v2.2.1, my typscript compiler complains when assigning a value of type `Auth0Plugin` to a variable defined as type `Auth0VueClient`.

Error:
```ts
plugins/1.auth0.server.ts:10:5 - error TS2322: Type 'Auth0Plugin' is not assignable to type 'Auth0VueClient'.
  The types of 'user.value' are incompatible between these types.
    Type '{ readonly [x: string]: any; readonly name?: string | undefined; readonly given_name?: string | undefined; readonly family_name?: string | undefined; readonly middle_name?: string | undefined; ... 15 more ...; readonly sub?: string | undefined; } | undefined' is not assignable to type 'User | undefined'.
      Type '{ readonly [x: string]: any; readonly name?: string | undefined; readonly given_name?: string | undefined; readonly family_name?: string | undefined; readonly middle_name?: string | undefined; ... 15 more ...; readonly sub?: string | undefined; }' is not assignable to type 'User' with 'exactOptionalPropertyTypes: true'. Consider adding 'undefined' to the types of the target's properties.
        Types of property 'name' are incompatible.
          Type 'string | undefined' is not assignable to type 'string'.
            Type 'undefined' is not assignable to type 'string'.
```

The types of the values `user` of the interface `Auth0VueClient` and the class `Auth0Plugin` are incompatible in that the class defines it as:
```ts
export declare class Auth0Plugin implements Auth0VueClient {
    private clientOptions;
    private pluginOptions?;
    private _client;
    private _isLoading;
    private _isAuthenticated;
    private _user;
    private _idTokenClaims;
    private _error;
    isLoading: Readonly<Ref<boolean>>;
    isAuthenticated: Readonly<Ref<boolean>>;
    user: Readonly<Ref<{
        readonly [x: string]: any;
        readonly name?: string | undefined;
        readonly given_name?: string | undefined;
        readonly family_name?: string | undefined;
        readonly middle_name?: string | undefined;
        readonly nickname?: string | undefined;
        readonly preferred_username?: string | undefined;
        readonly profile?: string | undefined;
        readonly picture?: string | undefined;
        readonly website?: string | undefined;
        readonly email?: string | undefined;
        readonly email_verified?: boolean | undefined;
        readonly gender?: string | undefined;
        readonly birthdate?: string | undefined;
        readonly zoneinfo?: string | undefined;
        readonly locale?: string | undefined;
        readonly phone_number?: string | undefined;
        readonly phone_number_verified?: boolean | undefined;
        readonly address?: string | undefined;
        readonly updated_at?: string | undefined;
        readonly sub?: string | undefined;
    } | undefined>>;
```
... but the interface refers to the class `User` which is defined as:
```ts
export declare class User {
    name?: string;
    given_name?: string;
    family_name?: string;
    middle_name?: string;
    nickname?: string;
    preferred_username?: string;
    profile?: string;
    picture?: string;
    website?: string;
    email?: string;
    email_verified?: boolean;
    gender?: string;
    birthdate?: string;
    zoneinfo?: string;
    locale?: string;
    phone_number?: string;
    phone_number_verified?: boolean;
    address?: string;
    updated_at?: string;
    sub?: string;
    [key: string]: any;
}
```

When having the option `exactOptionalPropertyTypes` set to `true`, an optional property is different to an optional property which can also be undefined.

### Reproduction

1. Setting `exactOptionalPropertyTypes` to `true` in your Typescript configuration
2. Try to let this statement compile:
```ts
const foo = (plugin: Auth0Plugin) : Auth0VueClient => plugin
```

### Additional context

_No response_

### auth0-vue version

2.2.1

### Vue version

3.3.4

### Which browsers have you tested in?

Other

### PR DESCRIPTION
**Pull request by frederikprijck**
### Changes

Using `readonly()` kinda changes the types in such a way that it marks all properties as readonly. Instead of actual IdToken (or User) types, it's actualy using an inline type based on the IdToken (but marking everything as readonly).

This means that the Auth0VueClient interface defined properties such as IdTokenClaims as a `Ref<IdToken | undefined>`, the Auth0VuePlugin has them being inferred to as `DeepReadonly<UnwrapNestedRefs<IdToken>>`, which doesn't always align.

This can become complicated to type properly, while they don't really need to be marked as read-only. 

Dropping the read-only shouldn't cause issues, as they share the same public API:

```ts
const x = ref<IdToken>({__raw: 'abc'});
const xReadOnly = readonly(x);

console.log('raw', { x, xReadOnly }); // Logs x: RefImpl and xReadOnly: Proxy(RefImpl)
console.log('value', { x: x.value, xReadOnly: xReadOnly?.value }); // Logs 2x Proxy(Object)
console.log('property', { x: x.value.__raw, xReadOnly: xReadOnly?.value.__raw }); // Logs 2x 'abc'
```

With our SDK, the above would be:

```ts
console.log(auth0.idTokenClaims); // Logs RefImpl after this PR, Proxy(RefImpl) before this PR.
console.log(auth0.idTokenClaims.value); // Logs Proxy(Object) before and after this PR.
console.log(auth0.idTokenClaims.value.name); // Logs the correct claim value before and after this PR
```

As you can see, this should not change anything in how users can interact with our public reactive API.

### References

Closes #240 

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All code quality tools/guidelines have been run/followed

### CODE REVIEW

**Review by Widcket — APPROVED** [review]

**Comment by jonasingvar** [comment]
I was having this issue with the readonly properties (build would fail) and have confirmed it's working now with this fix. Thank you

**Review by stevehobbsdev — APPROVED** [review]
